name: Claude AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check-project:
    runs-on: ubuntu-latest
    outputs:
      project-exists: ${{ steps.check.outputs.exists }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check if project exists
        id: check
        run: |
          if [ -f "Frontida/Frontida.csproj" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  claude-review:
    needs: check-project
    if: needs.check-project.outputs.project-exists == 'true'
    runs-on: ubuntu-latest
    name: Claude Code Review
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: |
          cd Frontida
          dotnet restore

      - name: Build
        id: build
        run: |
          cd Frontida
          dotnet build --no-restore --configuration Release

      - name: Run tests
        id: test
        run: |
          cd Frontida
          dotnet test --no-build --configuration Release --verbosity normal || true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.cs
            **/*.cshtml
            **/*.razor
            **/*.csproj
            **/*.json

      - name: Analyze code changes
        if: steps.changed-files.outputs.any_changed == 'true'
        id: analyze
        uses: actions/github-script@v7
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Get changed files
            const changedFiles = '${{ steps.changed-files.outputs.all_changed_files }}'.split(' ');
            
            // Read file contents
            let fileContents = '';
            for (const file of changedFiles) {
              if (fs.existsSync(file)) {
                const content = fs.readFileSync(file, 'utf8');
                fileContents += `\n\n=== FILE: ${file} ===\n${content}`;
              }
            }
            
            // Call Claude API for code review
            const response = await fetch('https://api.anthropic.com/v1/messages', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-api-key': process.env.ANTHROPIC_API_KEY,
                'anthropic-version': '2023-06-01'
              },
              body: JSON.stringify({
                model: 'claude-sonnet-4-20250514',
                max_tokens: 4000,
                messages: [{
                  role: 'user',
                  content: `You are reviewing code for Frontida, a caregiving platform built with .NET 10 and SQL Server.
            
            Please review the following code changes with focus on:
            
            1. **Code Quality**
               - Follow C# and .NET best practices
               - Proper use of async/await patterns
               - LINQ query optimization
               - Proper exception handling
            
            2. **Security**
               - SQL injection prevention (EF Core parameterization)
               - Input validation
               - Authorization checks
               - Secure data handling (passwords, personal info)
               - CSRF protection
            
            3. **Architecture**
               - Separation of concerns
               - Repository pattern usage
               - Service layer implementation
               - Dependency injection
            
            4. **Entity Framework**
               - Efficient queries (avoid N+1 problems)
               - Proper use of Include/ThenInclude
               - Migration quality
               - Index usage
            
            5. **ASP.NET Core MVC**
               - Controller action design
               - Model binding and validation
               - View model usage
               - Razor syntax
            
            6. **Performance**
               - Database query efficiency
               - Caching opportunities
               - Async operations
               - Memory management
            
            Provide specific, actionable feedback. Be constructive and educational.
            
            Changed files and their contents:
            ${fileContents}`
                }]
              })
            });
            
            const data = await response.json();
            const review = data.content[0].text;
            
            // Save review to output
            core.setOutput('review', review);
            return review;

      - name: Comment PR with Review
        if: steps.analyze.outputs.review
        uses: actions/github-script@v7
        with:
          script: |
            const review = `${{ steps.analyze.outputs.review }}`;
            
            const output = `## 🤖 Claude AI Code Review
            
            ${review}
            
            ---
            
            ### Build Summary
            - Build: ${{ steps.build.outcome }}
            - Tests: ${{ steps.test.outcome }}
            
            *Powered by Claude Sonnet 4.5*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Code Quality Check
        if: needs.check-project.outputs.project-exists == 'true'
        run: |
          cd Frontida
          dotnet format --verify-no-changes --verbosity diagnostic || true

  no-project-warning:
    needs: check-project
    if: needs.check-project.outputs.project-exists == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **No .NET project found**\n\nThe Frontida project has not been initialized yet. Please create Issue #1 "Initial .NET 10 Project Setup" or manually run the "Initialize Frontida Project" workflow to set up the project structure.\n\nOnce the project is initialized, this workflow will automatically review your code changes.'
            });
